name: Build GitHub Pages - Cron

on:
 schedule:
   - cron:  "59 */4 * * *"

jobs:
  upload-data:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${ hashFiles('setup.py') }-${ hashFiles('dev-requirements.txt') }

    - name: Test
      uses: nuuuwan/python-repo-test@v1

    - name: Run - Upload Data
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        python src/news_lk2/gh-pages/build.py

    - name: Checkout repo branch gh-pages
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        token: "${{ secrets.REPO_DATA_TOKEN }}"

    - name: Copy data, and push to repo branch data
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        cp -r /tmp/news_lk2-gh-pages/* .
        git add .
        git commit -m "Updated gh-pages $(date)"
        git push origin gh-pages
